package org.enthusia.tags.rewards;

public enum RewardCriterionType {
    PLAYTIME_ACTIVE_MINUTES,
    PLAYTIME_AFK_MINUTES,
    PLAYTIME_TOTAL_MINUTES,
    PLAYTIME_CONSECUTIVE_ACTIVE_MINUTES,
    UNDERGROUND_ACTIVE_MINUTES,
    KILLS_TOTAL,
    DEATHS_TOTAL,
    BLOCK_MINED,
    KILL_STREAK_CURRENT,
    DEATH_STREAK_SAME,
    QUICK_KILL_COUNT,
    KILL_FULL_ARMOR_COUNT,
    KILL_LOW_HEALTH_COUNT,
    DEATH_CAUSE_COUNT,
    BALANCE_AT_LEAST,
    BALTOP_TOP3,
    PING_MS_AT_LEAST,
    STEPS_WALKED,
    PROJECTILE_HITS,
    CUSTOM_COUNTER
}
